<?php
$us_states = array(
				"ALABAMA"	=> 	"AL",
				"ALASKA" 	=>	"AK",
				"AMERICAN SAMOA" => "AS",
				"ARIZONA" 	=>	"AZ",
				"ARKANSAS"	=>	"AR",
				"CALIFORNIA"    =>	"CA",
				"COLORADO"	=>	"CO",
				"CONNECTICUT"   =>	"CT",
				"DELAWARE"	=>	"DE",
				"DISTRICT OF COLUMBIA"	=>	"DC",
				"FEDERATED STATES OF MICRONESIA"	=>	"FM",
				"FLORIDA"	=>	"FL",
				"GEORGIA"	=>	"GA",
				"GUAM"		=>	"GU",
				"HAWAII"	=>	"HI",
				"IDAHO"		=>	"ID",
				"ILLINOIS"	=>	"IL",
				"INDIANA"	=>	"IN",
				"IOWA"		=>	"IA",
				"KANSAS"	=>	"KS",
				"KENTUCKY"	=>	"KY",
				"LOUISIANA"	=>	"LA",
				"MAINE"		=>	"ME",
				"MARSHALL ISLANDS"	=>	"MH",
				"MARYLAND"	=>	"MD",
				"MASSACHUSETTS"	=>	"MA",
				"MICHIGAN"	=>	"MI",
				"MINNESOTA"	=>	"MN",
				"MISSISSIPPI"   =>	"MS",
				"MISSOURI"	=>	"MO",
				"MONTANA"	=>	"MT",
				"NEBRASKA"	=>	"NE",
				"NEVADA"	=>	"NV",
				"NEW HAMPSHIRE"	=>	"NH",
				"NEW JERSEY"	=>	"NJ",
				"NEW MEXICO"	=>	"NM",
				"NEW YORK"	=>	"NY",
				"NORTH CAROLINA"=>	"NC",
				"NORTH DAKOTA"	=>	"ND",
				"NORTHERN MARIANA ISLANDS"	=>	"MP",
				"OHIO"		=>	"OH",
				"OKLAHOMA"	=>	"OK",
				"OREGON"	=>	"OR",
				"PALAU"		=>	"PW",
				"PENNSYLVANIA"	=>	"PA",
				"PUERTO RICO"	=>	"PR",
				"RHODE ISLAND"	=>	"RI",
				"SOUTH CAROLINA"=>	"SC",
				"SOUTH DAKOTA"	=>	"SD",
				"TENNESSEE"	=>	"TN",
				"TEXAS"		=>	"TX",
				"UTAH"		=>	"UT",
				"VERMONT"	=>	"VT",
				"VIRGIN ISLANDS"=>	"VI",
				"VIRGINIA"	=>	"VA",
				"WASHINGTON"	=>	"WA",
				"WEST VIRGINIA"	=>	"WV",
				"WISCONSIN"	=>	"WI",
				"WYOMING"	=>	"WY"
			);
			
$roles_array = array('','Student', 'Work Study', 'Administrator', 'Faculty', 'System Admin');

$status_array = array('','Active', 'Suspended');

$cond_array = array('','New','Good','Moderate','Poor','Damaged');

$error_msgs = array(
		"1" => "Authentication Failed",
		"2" => "Session Expired",
		"101" => "You can not delete this Account",
		"102" => "Account successfully deleted",
		"103" => "Error deleting the account",
		"104" => "Account successfully created",
		"105" => "Error occured while creating new account",
		"106" => "Password and Confirm Password doesnt match",
		"107" => "User ID is mandatory",
		"108" => "User ID already exist. Please try another one.",
		"109" => "Account Disabled",
		"110" => "Error disabling the account",
		"111" => "Account Enabled",
		"112" => "Error enabling the account"
	);
?>
